name: .NET and C++/CLI with Google Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Setup C++ compiler and dependencies for Google Test
    - name: Install C++ build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake

    # Restore .NET dependencies
    - name: Restore .NET dependencies
      run: dotnet restore

    # Build .NET project
    - name: Build .NET project
      run: dotnet build --no-restore

    # Build C++/CLI project with Google Test
    - name: Build C++/CLI project with Google Test
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    # Run .NET tests
    - name: Run .NET tests
      run: dotnet test --no-build --verbosity normal

    # Run Google Test tests
    - name: Run Google Test tests
      run: |
        cd build
        ctest --output-on-failure
