name: MSBuild and Test
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  SOLUTION_FILE_PATH: ./educonnect-desktop-app.sln
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy MySql.Data.dll to build directory
      run: cp ${{ github.workspace }}/x64/res/MySql.Data.dll ${{ github.workspace }}/x64/Debug/
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}/x64/Debug
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
  test:
    runs-on: windows-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd x64/Debug
        ./educonnect-test.exe
